# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['normalize', 'normalize2', 'fun', 'fun2', 'fun3']

# Cell
import numpy as np

# Cell
def normalize(
    data: np.ndarray, # input data
    )->np.ndarray: # normalized data
    "Function normalizes the given input"
    return (data - np.min(data))/(np.max(data) - np.min(data))

# Cell
def normalize2(
    data: np.ndarray, # input data
    )->np.ndarray: # normalized data
    "Function normalizes the given input"
    return (data - np.min(data))/(np.max(data) - np.min(data))

# Cell
def fun(
    x: int, # input data
    y: int, # input data
    z: int, # input data
    )->int: # sum
    "adds number in the args"
    return x + y + z

# Cell
def fun2(
    x: int, # input data
    y: int, # input data
    z: int, # input data
    )->int: # sum
    "adds number in the args"
    return x + y + z

# Cell
def fun3(
    x: int, # input data
    y: int, # input data
    z: int, # input data
    )->int: # sum
    "adds number in the args"
    return x + y + z